import { Ingredient, Meal } from "./types";

export const ingredients: Ingredient[] = [
  { id: "chicken", name: "Chicken" },
  { id: "lamb", name: "Lamb" },
  { id: "ground-beef", name: "Ground beef" },
  { id: "diced-beef", name: "Diced beef" },
  { id: "pork-fillet", name: "Pork fillet" },
  { id: "prawns", name: "Prawns" },
  { id: "tuna", name: "Tuna" },
  { id: "smoked-salmon", name: "Smoked salmon" },
  { id: "bagels", name: "Bagels" },
  { id: "cream-cheese", name: "Cream cheese" },
  { id: "radishes", name: "Radishes" },
  { id: "large-tortillas", name: "Large tortillas" },
  { id: "red-onion", name: "Red onion" },
  { id: "tomato", name: "Tomato" },
  { id: "beans", name: "Beans" },
  { id: "broccoli", name: "Broccoli" },
  { id: "mushrooms", name: "Mushrooms" },
  { id: "creme-fraiche", name: "Creme fraiche" },
  { id: "rice", name: "Rice" },
  { id: "chickpeas", name: "Chickpeas" },
  { id: "pasta", name: "Pasta" },
  { id: "tomato-sauce", name: "Tomato sauce" },
  { id: "steaks", name: "Steaks" },
  { id: "white-beans", name: "White beans" },
  { id: "black-beans", name: "Black beans" },
  { id: "garlic", name: "Garlic" },
  { id: "rosemary", name: "Rosemary" },
  { id: "brown-bread", name: "Brown bread" },
  { id: "avocados", name: "Avocados" },
  { id: "hummus", name: "Hummus" },
  { id: "lime", name: "Lime" },
  { id: "lemon", name: "Lemon" },
  { id: "eggs", name: "Eggs" },
  { id: "fish", name: "Fish" },
  { id: "potatoes", name: "Potatoes" },
  { id: "shallots", name: "Shallots" },
  { id: "bell-pepper", name: "Bell pepper" },
  { id: "milk", name: "Milk" },
  { id: "parmesan", name: "Parmesan" },
  { id: "grana-padano", name: "Grana Padano" },
  { id: "lardons", name: "Lardons" },
  { id: "asparagus", name: "Asparagus" },
  { id: "white-wine", name: "White wine" },
  { id: "new-potatoes", name: "New potatoes" },
  { id: "green-veg", name: "Green veg" },
  { id: "mint-sauce", name: "Mint sauce" },
  { id: "pickled-peppers", name: "Pickled peppers" },
  { id: "fennel-seeds", name: "Fennel seeds" },
  { id: "cheese", name: "Cheese" },
  { id: "feta", name: "Feta" },
  { id: "greek-yogurt", name: "Greek yogurt" },
  { id: "shredded-cheese", name: "Shredded cheese" },
  { id: "buns", name: "Buns" },
  { id: "sauce", name: "Sauce" },
  { id: "lettuce", name: "Lettuce" },
  { id: "chard", name: "Chard" },
  { id: "gnocchi", name: "Gnocchi" },
  { id: "spinach", name: "Spinach" },
  { id: "basil", name: "Basil" },
  { id: "pine-nuts", name: "Pine nuts" },
  { id: "pita-bread", name: "Pita bread" },
];

export const meals: Meal[] = [
  {
    id: "creamy-chic-broc",
    name: "Creamy Chic Broc",
    imageUrl: "./img-meals/chic-broc.jpg",
    ingredients: ["chicken", "broccoli", "mushrooms", "creme-fraiche", "rice"],
    tags: {
      cookingMethod: "pot-pan",
      base: "rice",
      proteinSource: "chicken",
      convenience: ["batchable", "fridge-friendly"],
    },
  },
  {
    id: "fishy-pasta",
    name: "Fishy pasta",
    imageUrl: "./img-meals/fishy-pasta.jpg",
    ingredients: ["pasta", "fish", "creme-fraiche", "shallots", "asparagus", "white-wine", "lemon"],
    tags: {
      cookingMethod: "pot-pan",
      base: "pasta",
      proteinSource: "fish",
      convenience: [],
    },
  },
  {
    id: "epic-beans-and-steak",
    name: "Epic beans and steak",
    imageUrl: "./img-meals/epic-beans-steak.jpg",
    ingredients: ["steaks", "white-beans", "mushrooms", "garlic", "rosemary"],
    tags: {
      cookingMethod: "pan",
      base: "beans",
      proteinSource: "beef",
      convenience: ["one-pot"],
    },
  },
  {
    id: "mexican-style-bean-casserole",
    name: "Mexican-style bean casserole",
    imageUrl: "./img-meals/mex-bean-casserole.jpg",
    ingredients: ["eggs", "black-beans", "avocados", "bell-pepper", "lime", "diced-beef"],
    tags: {
      cookingMethod: "pan",
      base: "beans",
      proteinSource: "beef",
      convenience: ["one-pot", "batchable", "fridge-friendly"],
    },
  },
  {
    id: "avocado-toast",
    name: "Avocado toast",
    imageUrl: "./img-meals/avocado-toasts.jpg",
    ingredients: ["brown-bread", "avocados", "lime", "eggs", "hummus", "mint-sauce"],
    tags: {
      cookingMethod: "pot",
      base: "bread",
      proteinSource: "eggs",
      convenience: ["one-pot"],
    },
  },
  {
    id: "burgers",
    name: "Burgers",
    imageUrl: "./img-meals/burgers.jpg",
    ingredients: ["buns", "sauce", "ground-beef", "cheese", "lettuce", "potatoes"],
    tags: {
      cookingMethod: "pan",
      base: "bread",
      proteinSource: "beef",
      convenience: ["one-pot"],
    },
  },
  {
    id: "chickpea-chard-pork",
    name: "Chickpea chard pork",
    imageUrl: "./img-meals/chickpea-chard-pork.jpg",
    ingredients: ["pork-fillet", "chickpeas", "chard", "pickled-peppers", "fennel-seeds"],
    tags: {
      cookingMethod: "pan",
      base: "chickpeas",
      proteinSource: "pork",
      convenience: ["one-pot", "batchable", "fridge-friendly"],
    },
  },
  {
    id: "pesto-chicken-gnocchi",
    name: "Pesto chicken gnocchi",
    imageUrl: "./img-meals/pesto-chicken-gnocchi.jpg",
    ingredients: ["chicken", "gnocchi", "spinach", "basil", "pine-nuts", "parmesan"],
    tags: {
      cookingMethod: "pan",
      base: "gnocchi",
      proteinSource: "chicken",
      convenience: ["one-pot", "fridge-friendly"],
    },
  },
  {
    id: "pasta-bolognese",
    name: "Pasta bolognese",
    imageUrl: "./img-meals/pasta-bolognese.jpg",
    ingredients: ["pasta", "tomato-sauce", "ground-beef"],
    tags: {
      cookingMethod: "pot",
      base: "pasta",
      proteinSource: "beef",
      convenience: ["one-pot", "fridge-friendly", "batchable"],
    },
  },
  {
    id: "pasta-carbonara",
    name: "Pasta carbonara",
    imageUrl: "./img-meals/pasta-carbonara.jpg",
    ingredients: ["pasta", "eggs", "grana-padano", "parmesan", "lardons", "mushrooms"],
    tags: {
      cookingMethod: "pot-pan",
      base: "pasta",
      proteinSource: "pork",
      convenience: [],
    },
  },
  {
    id: "fish-n-mash",
    name: "Fish n mash",
    imageUrl: "./img-meals/fisn-n-mash.jpg",
    ingredients: ["fish", "potatoes", "shallots", "bell-pepper", "milk"],
    tags: {
      cookingMethod: "pot-pan",
      base: "potatoes",
      proteinSource: "fish",
      convenience: ["fridge-friendly"],
    },
  },
  {
    id: "pan-seared-lamb",
    name: "Pan-seared lamb",
    ingredients: ["lamb", "potatoes", "green-veg", "mint-sauce"],
    tags: {
      cookingMethod: "pot-pan",
      base: "potatoes",
      proteinSource: "lamb",
      convenience: [],
    },
  },
  {
    id: "prawn-burritos",
    name: "Prawn burritos",
    imageUrl: "./img-meals/prawn-burritos.jpg",
    ingredients: ["prawns", "large-tortillas", "avocados", "tomato", "red-onion", "lime", "beans", "shredded-cheese"],
    tags: {
      cookingMethod: "pan",
      base: "tortillas",
      proteinSource: "seafood",
      convenience: ["sandwich", "one-pot"],
    },
  },
  {
    id: "tuna-pita",
    name: "Tuna pita sandwiches",
    imageUrl: "./img-meals/tuna-pita.jpg",
    ingredients: ["tuna", "pita-bread", "avocados", "pickled-peppers", "feta", "greek-yogurt"],
    tags: {
      cookingMethod: "no-cook",
      base: "bread",
      proteinSource: "fish",
      convenience: ["sandwich", "fridge-friendly"],
    },
  },
  {
    id: "salmon-bagels",
    name: "Smoked salmon bagels",
    imageUrl: "./img-meals/salmon-bagels.jpg",
    ingredients: ["smoked-salmon", "bagels", "cream-cheese", "radishes", "spinach"],
    tags: {
      cookingMethod: "no-cook",
      base: "bread",
      proteinSource: "fish",
      convenience: ["sandwich"],
    },
    // TODO: add seasoning staples prop. Will be in its own section of grocery list
    // Recommended seasoning: dill, lemon juice, balsamic vinegar, pepper
  },
];

export const getIngredientById = (id: string): Ingredient | null => {
  return ingredients.find(ingredient => ingredient.id === id) || null;
};

export const getMealById = (id: string): Meal | null => {
  return meals.find(meal => meal.id === id) || null;
};
