import { Ingredient } from "@/models/types";

// Enum for ingredient IDs to prevent arbitrary additions
export enum IngredientId {
  CHICKEN = "chicken",
  LAMB = "lamb",
  GROUND_BEEF = "ground-beef",
  DICED_BEEF = "diced-beef",
  BEEF = "beef",
  PORK_FILLET = "pork-fillet",
  HAM = "ham",
  PRAWNS = "prawns",
  TUNA = "tuna",
  SMOKED_SALMON = "smoked-salmon",
  BAGELS = "bagels",
  CREAM_CHEESE = "cream-cheese",
  RADISHES = "radishes",
  LARGE_TORTILLAS = "large-tortillas",
  RED_ONION = "red-onion",
  WHITE_ONION = "white-onion",
  TOMATO = "tomato",
  BEANS = "beans",
  BROCCOLI = "broccoli",
  MUSHROOMS = "mushrooms",
  CREME_FRAICHE = "creme-fraiche",
  RICE = "rice",
  CHICKPEAS = "chickpeas",
  PASTA = "pasta",
  TOMATO_SAUCE = "tomato-sauce",
  STEAKS = "steaks",
  WHITE_BEANS = "white-beans",
  BLACK_BEANS = "black-beans",
  GARLIC = "garlic",
  ROSEMARY = "rosemary",
  BROWN_BREAD = "brown-bread",
  BREAD = "bread",
  PITA_BREAD = "pita-bread",
  AVOCADOS = "avocados",
  HUMMUS = "hummus",
  LIME = "lime",
  LEMON = "lemon",
  EGGS = "eggs",
  FISH = "fish",
  POTATOES = "potatoes",
  SHALLOTS = "shallots",
  BELL_PEPPER = "bell-pepper",
  MILK = "milk",
  PARMESAN = "parmesan",
  MOZZARELLA = "mozzarella",
  GRANA_PADANO = "grana-padano",
  LARDONS = "lardons",
  ASPARAGUS = "asparagus",
  WHITE_WINE = "white-wine",
  RED_WINE = "red-wine",
  NEW_POTATOES = "new-potatoes",
  PEARL_COUSCOUS = "pearl-couscous",
  GREEN_VEG = "green-veg",
  MINT_SAUCE = "mint-sauce",
  PICKLED_PEPPERS = "pickled-peppers",
  FENNEL_SEEDS = "fennel-seeds",
  CHEESE = "cheese",
  FETA = "feta",
  GREEK_YOGURT = "greek-yogurt",
  SHREDDED_CHEESE = "shredded-cheese",
  BUNS = "buns",
  SAUCE = "sauce",
  LETTUCE = "lettuce",
  CHARD = "chard",
  GNOCCHI = "gnocchi",
  SPINACH = "spinach",
  FRESH_BASIL = "fresh-basil",
  PINE_NUTS = "pine-nuts",
  SALMON = "salmon",
  TENDERSTEM_BROCCOLI = "tenderstem-broccoli",
  CARROTS = "carrots",
  PARSNIPS = "parsnips",
  FLAT_BEANS = "flat-beans",
  SPRING_ONION = "spring-onion",
  CABBAGE = "cabbage",
  PISTACHIOS = "pistachios",
  RICOTTA = "ricotta",
  HONEY = "honey",
  PARSLEY = "parsley",
  MASCARPONE = "mascarpone",
  FISH_BROTH = "fish-broth",
  BEEF_BROTH = "beef-broth",
  VEGETABLE_BROTH = "vegetable-broth",
  CHICKEN_BROTH = "chicken-broth",
  BEAN_SPROUTS = "bean-sprouts",
  ROCKET = "rocket",
  PROSCIUTTO = "prosciutto",
  FOCACCIA = "focaccia",
}

// Enum for seasoning staple IDs
export enum SeasoningStapleId {
  OLIVE_OIL = "olive-oil",
  BUTTER = "butter",
  PAPRIKA = "paprika",
  PAPRIKA_MIX = "paprika-mix",
  GARLIC_POWDER_MIX = "garlic-powder-mix",
  DILL = "dill",
  ROSEMARY = "rosemary",
  LEMON_JUICE = "lemon-juice",
  BALSAMIC_VINEGAR = "balsamic-vinegar",
  RED_WINE_VINEGAR = "red-wine-vinegar",
  WHITE_WINE_VINEGAR = "white-wine-vinegar",
  CIDER_VINEGAR = "cider-vinegar",
  BLACK_PEPPER = "black-pepper",
  HONEY = "honey",
  SOY_SAUCE = "soy-sauce",
  SESAME_OIL = "sesame-oil",
  SESAME_SEEDS = "sesame-seeds",
  GINGER = "ginger",
  GARLIC_PASTE = "garlic-paste",
  TAHINI = "tahini",
  TARRAGON = "tarragon",
  SAFFRON = "saffron",
  BOUQUET_GARNI = "bouquet-garni",
  CLOVES = "cloves",
}

export const ingredients: Ingredient[] = [
  { id: IngredientId.CHICKEN, name: "Chicken" },
  { id: IngredientId.LAMB, name: "Lamb" },
  { id: IngredientId.GROUND_BEEF, name: "Ground beef" },
  { id: IngredientId.DICED_BEEF, name: "Diced beef" },
  { id: IngredientId.PORK_FILLET, name: "Pork fillet" },
  { id: IngredientId.PRAWNS, name: "Prawns" },
  { id: IngredientId.TUNA, name: "Tuna" },
  { id: IngredientId.SMOKED_SALMON, name: "Smoked salmon" },
  { id: IngredientId.BAGELS, name: "Bagels" },
  { id: IngredientId.CREAM_CHEESE, name: "Cream cheese" },
  { id: IngredientId.RADISHES, name: "Radishes" },
  { id: IngredientId.LARGE_TORTILLAS, name: "Large tortillas" },
  { id: IngredientId.RED_ONION, name: "Red onion" },
  { id: IngredientId.WHITE_ONION, name: "White onion" },
  { id: IngredientId.TOMATO, name: "Tomato" },
  { id: IngredientId.BEANS, name: "Beans" },
  { id: IngredientId.BROCCOLI, name: "Broccoli" },
  { id: IngredientId.MUSHROOMS, name: "Mushrooms" },
  { id: IngredientId.CREME_FRAICHE, name: "Creme fraiche" },
  { id: IngredientId.RICE, name: "Rice" },
  { id: IngredientId.CHICKPEAS, name: "Chickpeas" },
  { id: IngredientId.PASTA, name: "Pasta" },
  { id: IngredientId.TOMATO_SAUCE, name: "Tomato sauce" },
  { id: IngredientId.STEAKS, name: "Steaks" },
  { id: IngredientId.WHITE_BEANS, name: "White beans" },
  { id: IngredientId.BLACK_BEANS, name: "Black beans" },
  { id: IngredientId.GARLIC, name: "Garlic" },
  { id: IngredientId.ROSEMARY, name: "Rosemary" },
  { id: IngredientId.BROWN_BREAD, name: "Brown bread" },
  { id: IngredientId.BREAD, name: "Bread" },
  { id: IngredientId.PITA_BREAD, name: "Pita bread" },
  { id: IngredientId.AVOCADOS, name: "Avocados" },
  { id: IngredientId.HUMMUS, name: "Hummus" },
  { id: IngredientId.LIME, name: "Lime" },
  { id: IngredientId.LEMON, name: "Lemon" },
  { id: IngredientId.EGGS, name: "Eggs" },
  { id: IngredientId.FISH, name: "Fish" },
  { id: IngredientId.POTATOES, name: "Potatoes" },
  { id: IngredientId.SHALLOTS, name: "Shallots" },
  { id: IngredientId.BELL_PEPPER, name: "Bell pepper" },
  { id: IngredientId.MILK, name: "Milk" },
  { id: IngredientId.PARMESAN, name: "Parmesan" },
  { id: IngredientId.MOZZARELLA, name: "Mozzarella" },
  { id: IngredientId.GRANA_PADANO, name: "Grana Padano" },
  { id: IngredientId.LARDONS, name: "Lardons" },
  { id: IngredientId.ASPARAGUS, name: "Asparagus" },
  { id: IngredientId.WHITE_WINE, name: "White wine" },
  { id: IngredientId.NEW_POTATOES, name: "New potatoes" },
  { id: IngredientId.PEARL_COUSCOUS, name: "Pearl couscous" },
  { id: IngredientId.GREEN_VEG, name: "Green veg" },
  { id: IngredientId.MINT_SAUCE, name: "Mint sauce" },
  { id: IngredientId.PICKLED_PEPPERS, name: "Pickled peppers" },
  { id: IngredientId.FENNEL_SEEDS, name: "Fennel seeds" },
  { id: IngredientId.CHEESE, name: "Cheese" },
  { id: IngredientId.FETA, name: "Feta" },
  { id: IngredientId.GREEK_YOGURT, name: "Greek yogurt" },
  { id: IngredientId.SHREDDED_CHEESE, name: "Shredded cheese" },
  { id: IngredientId.BUNS, name: "Buns" },
  { id: IngredientId.SAUCE, name: "Sauce" },
  { id: IngredientId.LETTUCE, name: "Lettuce" },
  { id: IngredientId.CHARD, name: "Chard" },
  { id: IngredientId.GNOCCHI, name: "Gnocchi" },
  { id: IngredientId.SPINACH, name: "Spinach" },
  { id: IngredientId.FRESH_BASIL, name: "Fresh basil" },
  { id: IngredientId.PINE_NUTS, name: "Pine nuts" },
  { id: IngredientId.SALMON, name: "Salmon" },
  { id: IngredientId.TENDERSTEM_BROCCOLI, name: "Tenderstem broccoli" },
  { id: IngredientId.CARROTS, name: "Carrots" },
  { id: IngredientId.FLAT_BEANS, name: "Flat beans" },
  { id: IngredientId.SPRING_ONION, name: "Spring onion" },
  { id: IngredientId.CABBAGE, name: "Cabbage" },
  { id: IngredientId.PISTACHIOS, name: "Pistachios" },
  { id: IngredientId.RICOTTA, name: "Ricotta" },
  { id: IngredientId.HONEY, name: "Honey" },
  { id: IngredientId.PARSLEY, name: "Parsley" },
  { id: IngredientId.MASCARPONE, name: "Mascarpone" },
  { id: IngredientId.FISH_BROTH, name: "Fish broth" },
  { id: IngredientId.BEEF_BROTH, name: "Beef broth" },
  { id: IngredientId.VEGETABLE_BROTH, name: "Vegetable broth" },
  { id: IngredientId.RED_WINE, name: "Red wine" },
  { id: IngredientId.BEEF, name: "Beef" },
  { id: IngredientId.HAM, name: "Ham" },
  { id: IngredientId.CHICKEN_BROTH, name: "Chicken broth" },
  { id: IngredientId.PARSNIPS, name: "Parsnips" },
  { id: IngredientId.BEAN_SPROUTS, name: "Bean sprouts" },
  { id: IngredientId.ROCKET, name: "Rocket" },
  { id: IngredientId.PROSCIUTTO, name: "Prosciutto" },
  { id: IngredientId.FOCACCIA, name: "Focaccia" },
];

export const seasoningStaples: Ingredient[] = [
  { id: SeasoningStapleId.OLIVE_OIL, name: "Olive oil" },
  { id: SeasoningStapleId.BUTTER, name: "Butter" },
  { id: SeasoningStapleId.PAPRIKA, name: "Paprika" },
  { id: SeasoningStapleId.PAPRIKA_MIX, name: "Paprika mix" },
  { id: SeasoningStapleId.GARLIC_POWDER_MIX, name: "Garlic powder mix" },
  { id: SeasoningStapleId.DILL, name: "Dill" },
  { id: SeasoningStapleId.ROSEMARY, name: "Rosemary" },
  { id: SeasoningStapleId.LEMON_JUICE, name: "Lemon juice" },
  { id: SeasoningStapleId.BALSAMIC_VINEGAR, name: "Balsamic vinegar" },
  { id: SeasoningStapleId.RED_WINE_VINEGAR, name: "Red wine vinegar" },
  { id: SeasoningStapleId.WHITE_WINE_VINEGAR, name: "White wine vinegar" },
  { id: SeasoningStapleId.CIDER_VINEGAR, name: "Cider vinegar" },
  { id: SeasoningStapleId.BLACK_PEPPER, name: "Black pepper" },
  { id: SeasoningStapleId.HONEY, name: "Honey" },
  { id: SeasoningStapleId.SOY_SAUCE, name: "Soy sauce" },
  { id: SeasoningStapleId.SESAME_OIL, name: "Sesame oil" },
  { id: SeasoningStapleId.SESAME_SEEDS, name: "Sesame seeds" },
  { id: SeasoningStapleId.GINGER, name: "Ginger" },
  { id: SeasoningStapleId.GARLIC_PASTE, name: "Garlic paste" },
  { id: SeasoningStapleId.TAHINI, name: "Tahini" },
  { id: SeasoningStapleId.TARRAGON, name: "Tarragon" },
  { id: SeasoningStapleId.SAFFRON, name: "Saffron" },
  { id: SeasoningStapleId.BOUQUET_GARNI, name: "Bouquet garni" },
  { id: SeasoningStapleId.CLOVES, name: "Cloves" },
];

export const getIngredientById = (id: string): Ingredient | null => {
  return ingredients.find(ingredient => ingredient.id === id) ||
         seasoningStaples.find(seasoning => seasoning.id === id) ||
         null;
};
